services:
  # NestJS 서비스
  backend:
    build:
      context: .
    container_name: nestjs-backend
    ports:
      - '3000:3000'
    env_file:
      - .dev.env
    depends_on:
      - db
    networks:
      - app-network

  # MySQL 서비스
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      container_name: mysql-db
      MYSQL_ROOT_PASSWORD: '0000' # MySQL root 비밀번호
      MYSQL_USER: 'test' # MySQL 사용자
      MYSQL_PASSWORD: '0000' # 사용자 비밀번호
      MYSQL_DATABASE: 'mydatabase' # 기본 데이터베이스 이름
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

# 네트워크 설정
networks:
  app-network:
    driver: bridge

# 데이터 볼륨 설정
volumes:
  mysql-data:
