services:
  # NestJS 서비스
  backend:
    build:
      context: .
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - app-network

  # MySQL 서비스
  db:
    image: mysql:5.7
    container_name: mysql-db
    env_file:
      - .env.dev
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

# 네트워크 설정
networks:
  app-network:
    driver: bridge

# 데이터 볼륨 설정
volumes:
  mysql-data:
